<a href="https://colab.research.google.com/github/THIRU9573/Tensorflow-Notes/blob/main/Tensorflow_Class_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

TensorFolw is an end to end platform for machine learning. it support following : 1.Multidimentional array based numeric computation 2.GPU and distributed processing 3.Automatic differention 4.Model construction,training and export and more

## ***Tensors***

Tensorflow operate on multidimential array or tensors represented as tf.tTensor objects. Here is two dimentional tensor: 

In [3]:
import tensorflow as tf
x = tf.constant([[1.,2.,3.],
                  [4.,5.,6.]]) 
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>


The most important attributes of a tf.Tensor are its shape and dtype:


1.   Tensor.shape:tells you the size of the tensor along each of its axes
2.  Tensor.dtype:tells you the type of all the elements in the tensor.
Tensorflow implement standard mathematical operations on tensors as well as many operations specialized for machine learning.
Foe Example:



In [4]:
x+x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [5]:
5*x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 5., 10., 15.],
       [20., 25., 30.]], dtype=float32)>

In [6]:
x @ tf.transpose(x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

The @ symbol in this context is the matrix multiplication operator in TensorFlow. It is equivalent to calling tf.matmul().

In [ ]:
from IPython.dispaly import Image
Image(filename = , width = 400,height = 400)

## tf.concat(values,axis)

tf.concat() is a function in TensorFlow, which is used to concatenate tensors along a given axis. It takes a list of tensors as input and returns a new tensor, which is the result of concatenating all the input tensors along the specified axis.

The syntax for using tf.concat() is as follows:

In [7]:
tf.concat([x,x,x], axis = 0)

<tf.Tensor: shape=(6, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [1., 2., 3.],
       [4., 5., 6.],
       [1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [8]:
A = tf.constant([[1,2,3],[4,5,6]])
B = tf.constant([[7,8,9,10],[11,12,13,14]])

C = tf.concat([A,B], axis = 1)
print(C)

tf.Tensor(
[[ 1  2  3  7  8  9 10]
 [ 4  5  6 11 12 13 14]], shape=(2, 7), dtype=int32)


In [10]:
A = tf.constant([[1,2,3,4],[4,5,6,7]])
B = tf.constant([[7,8,9,10],[11,12,13,14]])

C = tf.concat([A,B], axis = 0)
print(C)

tf.Tensor(
[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]
 [11 12 13 14]], shape=(4, 4), dtype=int32)


# tf.nn.softmax()

tf.nn.softmax() is a function in TensorFlow that computes the softmax activation function for a given input tensor. The softmax function is a commonly used activation function in neural networks, especially for multi-class classification problems.

The softmax function takes a vector of real-valued scores as input and normalizes them into a probability distribution over the classes. The output of the softmax function is a vector of probabilities, where each element represents the probability of the input belonging to a particular class.

The syntax for using tf.nn.softmax() is as follows:

In [11]:
#tf.nn.softmax(logits, axis=None, name=None)

In [13]:
tf.nn.softmax(x, axis = -1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.09003057, 0.24472848, 0.66524094],
       [0.09003057, 0.24472848, 0.66524094]], dtype=float32)>

## tf.reduce_sum():

tf.reduce_sum() is a function in TensorFlow that computes the sum of all the elements in a tensor, or along a specified axis of a tensor. It is a useful operation in various machine learning applications, such as computing the loss function or computing accuracy.

The syntax for using tf.reduce_sum() is as follows:

In [14]:
#tf.reduce_sum(input_tensor, axis=None, keepdims=False, name=None)


In [15]:
tf.reduce_sum(x)

<tf.Tensor: shape=(), dtype=float32, numpy=21.0>

In [16]:
tf.reduce_sum(x,axis = 1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 6., 15.], dtype=float32)>

In [17]:
tf.reduce_sum(x,axis = 0)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([5., 7., 9.], dtype=float32)>

In [22]:
y = tf.constant([[[1,2,3,],
                  [3,4,5],
                  [5,6,7]]])
a = tf.reduce_sum(y)
b = tf.reduce_sum(y,axis = 0)
c = tf.reduce_sum(y, axis = 1)
print(a)
print(b)
print(c)

tf.Tensor(36, shape=(), dtype=int32)
tf.Tensor(
[[1 2 3]
 [3 4 5]
 [5 6 7]], shape=(3, 3), dtype=int32)
tf.Tensor([[ 9 12 15]], shape=(1, 3), dtype=int32)


## tf.convet_to_tensor():

tf.convert_to_tensor() is a function in TensorFlow that converts a given value to a tensor. This function is useful when you want to ensure that a given value is represented as a tensor in TensorFlow, regardless of its original type or shape.

The syntax for using tf.convert_to_tensor() is as follows:

In [23]:
#tf.convert_to_tensor(value, dtype=None, dtype_hint=None, name=None)


In [24]:
tf.convert_to_tensor([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [26]:
z = [1,2,3,4,5]
u = tf.convert_to_tensor(z)
print(u)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [28]:
x = 3.14
v = tf.convert_to_tensor(x, dtype = tf.float32)
print(v)

tf.Tensor(3.14, shape=(), dtype=float32)


In [29]:
tf.reduce_sum(u)

<tf.Tensor: shape=(), dtype=int32, numpy=15>

In [30]:
tf.reduce_sum([1,3,4,5,7,9])

<tf.Tensor: shape=(), dtype=int32, numpy=29>

In [31]:
if tf.config.list_physical_devices('GPU'):
  print("TensorFlow **IS** using the GPU")
else:
  print("TensorFlow **IS NOT** using the GPU")

TensorFlow **IS NOT** using the GPU


## Variables:

Normal tf.Tensor objects are immutable. To store model weights (or other mutable state) in TensorFlow use a tf.Variable.

In [32]:
var = tf.Variable([0.0, 0.0,0.0])
var.assign([1,2,3])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [33]:
var.assign_add([1,1,1])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>

In [34]:
var.assign_sub([1,2,3])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

## Automatic Differentiation:

To enable this, TensorFlow implements automatic differentiation (autodiff), which uses calculus to compute gradients. Typically you'll use this to calculate the gradient of a model's error or loss with respect to its weights.

In [37]:
x = tf.Variable(1.0)

def f(x):
  y = x**2+2*x - 5
  return y

In [38]:
f(x)

<tf.Tensor: shape=(), dtype=float32, numpy=-2.0>

At x = 1.0, y = f(x) = (1**2 + 2*1 - 5) = -2.

The derivative of y is y' = f'(x) = (2*x + 2) = 4. TensorFlow can calculate this automatically:

In [40]:
with tf.GradientTape() as tape:
  y = f(x)
g_x = tape.gradient(y,x)   #g(x) = dy/dx
g_x

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>