<a href="https://colab.research.google.com/github/THIRU9573/Tensorflow-Notes/blob/main/Tensorflow_Class_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 import tensorflow as tf

TensorFolw is an end to end platform for machine learning. it support following : 1.Multidimentional array based numeric computation 2.GPU and distributed processing 3.Automatic differention 4.Model construction,training and export and more

## ***Tensors***

Tensorflow operate on multidimential array or tensors represented as tf.tTensor objects. Here is two dimentional tensor: 

In [2]:
import tensorflow as tf
x = tf.constant([[1.,2.,3.],
                  [4.,5.,6.]]) 
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>


The most important attributes of a tf.Tensor are its shape and dtype:


1.   Tensor.shape:tells you the size of the tensor along each of its axes
2.  Tensor.dtype:tells you the type of all the elements in the tensor.
Tensorflow implement standard mathematical operations on tensors as well as many operations specialized for machine learning.
Foe Example:



In [ ]:
x+x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [ ]:
5*x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 5., 10., 15.],
       [20., 25., 30.]], dtype=float32)>

In [ ]:
x @ tf.transpose(x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

The @ symbol in this context is the matrix multiplication operator in TensorFlow. It is equivalent to calling tf.matmul().

In [ ]:
from IPython.dispaly import Image
Image(filename = , width = 400,height = 400)

## tf.concat(values,axis)

tf.concat() is a function in TensorFlow, which is used to concatenate tensors along a given axis. It takes a list of tensors as input and returns a new tensor, which is the result of concatenating all the input tensors along the specified axis.

The syntax for using tf.concat() is as follows:

In [ ]:
tf.concat([x,x,x], axis = 0)

<tf.Tensor: shape=(6, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [1., 2., 3.],
       [4., 5., 6.],
       [1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [ ]:
A = tf.constant([[1,2,3],[4,5,6]])
B = tf.constant([[7,8,9,10],[11,12,13,14]])

C = tf.concat([A,B], axis = 1)
print(C)

tf.Tensor(
[[ 1  2  3  7  8  9 10]
 [ 4  5  6 11 12 13 14]], shape=(2, 7), dtype=int32)


In [ ]:
A = tf.constant([[1,2,3,4],[4,5,6,7]])
B = tf.constant([[7,8,9,10],[11,12,13,14]])

C = tf.concat([A,B], axis = 0)
print(C)

tf.Tensor(
[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]
 [11 12 13 14]], shape=(4, 4), dtype=int32)


# tf.nn.softmax()

tf.nn.softmax() is a function in TensorFlow that computes the softmax activation function for a given input tensor. The softmax function is a commonly used activation function in neural networks, especially for multi-class classification problems.

The softmax function takes a vector of real-valued scores as input and normalizes them into a probability distribution over the classes. The output of the softmax function is a vector of probabilities, where each element represents the probability of the input belonging to a particular class.

The syntax for using tf.nn.softmax() is as follows:

In [ ]:
#tf.nn.softmax(logits, axis=None, name=None)

In [ ]:
tf.nn.softmax(x, axis = -1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.09003057, 0.24472848, 0.66524094],
       [0.09003057, 0.24472848, 0.66524094]], dtype=float32)>

## tf.reduce_sum():

tf.reduce_sum() is a function in TensorFlow that computes the sum of all the elements in a tensor, or along a specified axis of a tensor. It is a useful operation in various machine learning applications, such as computing the loss function or computing accuracy.

The syntax for using tf.reduce_sum() is as follows:

In [ ]:
#tf.reduce_sum(input_tensor, axis=None, keepdims=False, name=None)


In [ ]:
tf.reduce_sum(x)

<tf.Tensor: shape=(), dtype=float32, numpy=21.0>

In [ ]:
tf.reduce_sum(x,axis = 1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 6., 15.], dtype=float32)>

In [ ]:
tf.reduce_sum(x,axis = 0)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([5., 7., 9.], dtype=float32)>

In [ ]:
y = tf.constant([[[1,2,3,],
                  [3,4,5],
                  [5,6,7]]])
a = tf.reduce_sum(y)
b = tf.reduce_sum(y,axis = 0)
c = tf.reduce_sum(y, axis = 1)
print(a)
print(b)
print(c)

tf.Tensor(36, shape=(), dtype=int32)
tf.Tensor(
[[1 2 3]
 [3 4 5]
 [5 6 7]], shape=(3, 3), dtype=int32)
tf.Tensor([[ 9 12 15]], shape=(1, 3), dtype=int32)


## tf.convet_to_tensor():

tf.convert_to_tensor() is a function in TensorFlow that converts a given value to a tensor. This function is useful when you want to ensure that a given value is represented as a tensor in TensorFlow, regardless of its original type or shape.

The syntax for using tf.convert_to_tensor() is as follows:

In [ ]:
#tf.convert_to_tensor(value, dtype=None, dtype_hint=None, name=None)


In [ ]:
tf.convert_to_tensor([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
z = [1,2,3,4,5]
u = tf.convert_to_tensor(z)
print(u)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [ ]:
x = 3.14
v = tf.convert_to_tensor(x, dtype = tf.float32)
print(v)

tf.Tensor(3.14, shape=(), dtype=float32)


In [ ]:
tf.reduce_sum(u)

<tf.Tensor: shape=(), dtype=int32, numpy=15>

In [ ]:
tf.reduce_sum([1,3,4,5,7,9])

<tf.Tensor: shape=(), dtype=int32, numpy=29>

In [ ]:
if tf.config.list_physical_devices('GPU'):
  print("TensorFlow **IS** using the GPU")
else:
  print("TensorFlow **IS NOT** using the GPU")

TensorFlow **IS NOT** using the GPU


## Variables:

Normal tf.Tensor objects are immutable. To store model weights (or other mutable state) in TensorFlow use a tf.Variable.

In [ ]:
var = tf.Variable([0.0, 0.0,0.0])
var.assign([1,2,3])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [ ]:
var.assign_add([1,1,1])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>

In [ ]:
var.assign_sub([1,2,3])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

## Automatic Differentiation:

To enable this, TensorFlow implements automatic differentiation (autodiff), which uses calculus to compute gradients. Typically you'll use this to calculate the gradient of a model's error or loss with respect to its weights.

In [ ]:
x = tf.Variable(1.0)

def f(x):
  y = x**2+2*x - 5
  return y

In [ ]:
f(x)

<tf.Tensor: shape=(), dtype=float32, numpy=-2.0>

At x = 1.0, y = f(x) = (1**2 + 2*1 - 5) = -2.

The derivative of y is y' = f'(x) = (2*x + 2) = 4. TensorFlow can calculate this automatically:

In [ ]:
with tf.GradientTape() as tape:
  y = f(x)
g_x = tape.gradient(y,x)   #g(x) = dy/dx
g_x

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

## Graphs and tf.function

While you can use Tensorflow interactivelylike  any Python library, TensorFlow also Privide tools for:


1.   Performance Optimization:to speed uptraining and inference
2.   Export:so you can save your model when its done training.

These require that you use tf.function to seperate your pure-Tensorflow code from Python



In [13]:
@tf.function
def my_func(x):
  print('Tracing. \n')
  return tf.reduce_sum(x)

The first time you run the tf.function, although its executes in Python, it captures  a completet, optimized graph reprenting the Tnsorflow computations done within the function.

In [14]:
x = tf.constant([1,2,3])
my_func(x)

Tracing. 



<tf.Tensor: shape=(), dtype=int32, numpy=6>

On subsequent calls TensorFlow only executes the optimized graph, skipping any non-TensorFlow steps. Below, note that my_func doesn't print tracing since print is a Python function, not a TensorFlow function.

In [15]:
x = tf.constant([10,9,8])
my_func(x)

<tf.Tensor: shape=(), dtype=int32, numpy=27>

 graph may not be reusable for inputs with a different signature (shape and dtype), so a new graph is generated instead:

In [16]:
x = tf.constant([10.0,9.1,8.2], dtype = tf.float32)
my_func(x)

Tracing. 



<tf.Tensor: shape=(), dtype=float32, numpy=27.3>

These captured graphs provude two benefits:


1.   in many cases they provide a significant  speedup in execution(through not this trival example).
2.   You can export these graphs, using tf.saved_model, to run on other systems like a server or a mobile device, no Python installation required.



## Modules,layers, and models

tf.Module is class for managing your tf.Variable objects and the tf.function objects thats operate on them. the tf.Module class is necessaryto supporttwo significants features:


1.   You can save and restore the values of your variables using tf.train.Checkpoint this is useful duringtraining as it is quick to save and retore a model's state
2.   You can import and export the tf.Variable values and the tf.function graphs using tf.saved_model. this allows yyou to run your model independently of the Python programe that created it.



Here is a Complete exporting a simple tf.Module object:

In [19]:
class MyProject(tf.Module):
  def __init__(self,value):
    self.weight = tf.Variable(value)
  
  @tf.function
  def multiply(self, x):
    return x*self.weight

mod = MyProject(3)
mod.multiply(tf.constant([1,2,3]))



<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 6, 9], dtype=int32)>

## Save the Module:

In [20]:
save_path = './saved'
tf.saved_model.save(mod, save_path)

The resulting savedModel is independent of the code that created it.you can load a savedModel from Python others language bindings, or Tensorflow serving you can also convert it to run with tensorflow lite or Tensorflow JS

In [21]:
reloaded = tf.saved_model.load(save_path)
reloaded.multiply(tf.constant([1,2,3]))

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 6, 9], dtype=int32)>

The tf.keras.layers.Layer and tf.keras.Model classes build on tf.Module providing additional functionality and convenience methods for building, training, and saving models. Some of these are demonstrated in the next section.

## Training loops

In [ ]:
import matplotlib
from matplotlib import pyplot as plt 
matplotlib.rcParams['figure.figsize'] = [9,6]